### ISSUE TITLE
Local repository for multiple servers

### ISSUE THREAD

**Issue by charlwentzel** [flexiondotorg/oab-java6#43]
On our LAN there are several virtual servers that require Sun Java.  Is it possible to use this technique to set up a local repository on a server which can be accessed by several servers on the LAN.  This will avoid installing the local repository for every machine and save a lot of time and bandwidth as well.

**Comment by flexiondotorg** [comment]
Hi,

I won't be adding this functionality to the script because there a many ways to implement this, many of which won't suite most people. But, you're right, once a build has been completed on one host you could use just about any file serving network protocol (http, ftp, nfs, etc) to share access to multiple hosts.

Regards, Martin.

**Comment by charlwentzel** [comment]
Hi Martin

Thanks for coming back to me so soon.  Is it possible to share it with 
apt as if it was a repository?  In other words could I add a link a 
references (similar to a PPA or repository) in the sources.list file of 
another machine and let them access it directly from there?

I usually add an apt-cacher-ng proxy server on my networks to reduces 
Internet load for updated a bunch of machines.  Could I follow a similar 
approach here.

My apologies for asking these basic questions, but I don't have 
extensive knowledge of the inner workings of sources and repositories.

Regards
Charl
